# Generated by Django 5.2.4 on 2025-08-11 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cristal_app', '0005_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='unidades_tarifa',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HORA', 'Por hora'), ('NOCHE', 'Por noche'), ('DIA', 'Por día')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='Cristal_app.habitacion')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'unique_together': {('habitacion', 'tipo')},
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='tarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='Cristal_app.tarifa'),
        ),
    ]
