# Generated by Django 5.2.4 on 2025-08-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cristal_app', '0006_reserva_unidades_tarifa_tarifa_reserva_tarifa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='tarifa',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='unidades_tarifa',
        ),
        migrations.DeleteModel(
            name='Tarifa',
        ),
    ]
