# Generated by Django 5.2.4 on 2025-08-15 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cristal_app', '0007_remove_reserva_tarifa_remove_reserva_unidades_tarifa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='precio_noche',
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('HORA', 'Hora'), ('DÍA', 'Día'), ('SEMANA', 'Semana')], max_length=10)),
                ('duracion', models.IntegerField()),
                ('hora_checkout', models.CharField(blank=True, max_length=5, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='Cristal_app.tipohabitacion')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
            },
        ),
    ]
