# Generated by Django 5.2.4 on 2025-08-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cristal_app', '0008_remove_habitacion_precio_noche_tarifa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifa',
            name='hora_checkout',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='precio_noche',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
