# Generated by Django 5.2.4 on 2025-08-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cristal_app', '0009_remove_tarifa_hora_checkout_habitacion_precio_noche'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tarifa',
            options={},
        ),
    ]
