# Generated by Django 5.2.4 on 2025-08-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cristal_app', '0010_alter_reserva_options_alter_tarifa_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='precio_noche',
        ),
    ]
