# Generated by Django 5.2.4 on 2025-08-15 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cristal_app', '0011_remove_habitacion_precio_noche'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifa',
            options={'verbose_name': 'Tarifa', 'verbose_name_plural': 'Tarifas'},
        ),
    ]
