# Generated by Django 5.2.4 on 2025-08-16 02:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cristal_app', '0012_alter_tarifa_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acompanante',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={},
        ),
        migrations.AddField(
            model_name='reserva',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='Cristal_app.tarifa'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='unidades_tarifa',
            field=models.PositiveIntegerField(default=1, help_text='p.ej., 1 noche, 2 noches, etc.'),
        ),
        migrations.AddField(
            model_name='tipopago',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='duracion',
            field=models.PositiveIntegerField(help_text='Horas si es HORA, días si es DÍA o SEMANA'),
        ),
    ]
